version: '3.8'
services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - DJANGO_SETTINGS_MODULE=base.settings
    volumes:
      - .:/app
    entrypoint: >
      sh -c "
      until nc -z mongo 27017; do
        echo 'Waiting for MongoDB...';
        sleep 1;
      done;
      echo 'MongoDB is ready!';
      echo 'ВНЕСЕНИЕ ТЕСТОВЫХ ДАННЫХ!';
      python create_test_data.py;
      python manage.py runserver 0.0.0.0:8000 & 
      echo 'Waiting for Django to start...';
      until nc -z localhost 8000; do
        sleep 1;
      done;
      echo 'Django is ready!';
      echo 'ВЫПОЛНЕНИЕ ТЕСТОВЫХ ЗАПРОСОВ!';
      python test_requests.py &&
      echo 'Были внесены тестовые данные и выполнены тестовые запросы, приложение полностью готово к эксплуатации!' &&
      wait
      "

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongod.conf  
    command: ["mongod", "--config", "/etc/mongod.conf"]  

volumes:
  mongo_data:
