version: '3.8'
services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - DJANGO_SETTINGS_MODULE=base.settings
    volumes:
      - .:/app
    entrypoint: >
      sh -c "
      until nc -z mongo 27017; do
        echo 'Waiting for MongoDB...';
        sleep 5;
      done;
      echo 'MongoDB is ready!';
      python create_test_data.py && python manage.py runserver 0.0.0.0:8000
      "

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
